export const koCopy = {
  brandName: "SSun Game",
  lobby: {
    ring: "링게임",
    sitAndGo: "Sit & Go",
    tournament: "토너먼트",
    chips: "칩",
    notifications: "알림",
    settings: "설정",
    changeAvatar: "변경",
    eventsTitle: "이벤트",
    recommendedTitle: "추천 게임",
    quickJoin: "빠른 참가",
    gamesTitle: "게임 선택",
    contentTitle: "진행 중인 이벤트 · 콘텐츠",
    enter: "입장",
    comingSoon: "준비 중",
    comingSoonHint: "서버 오픈 후 이용할 수 있어요",
    ringSubtitle: "0.1/0.2 · 2~9인 홀덤 테이블",
    sitAndGoSubtitle: "인원이 모이면 바로 시작",
    tournamentSubtitle: "정규 MTT · 시즌 포인트",
    recommendedRing: "지금 바로 링게임",
    recommendedRingSubtitle: "대기 없이 홀덤 테이블에 앉기",
    eventSeasonTitle: "시즌 1 오픈",
    eventSeasonSubtitle: "시즌 랭킹 보상이 기다립니다",
    eventSeasonLabel: "진행 중",
    eventMttTitle: "위클리 토너먼트",
    eventMttSubtitle: "매주 토요일 20:00",
    eventMttLabel: "준비 중",
    eventSngTitle: "Sit & Go 오픈 예정",
    eventSngSubtitle: "짧고 빠른 6인 테이블",
    eventSngLabel: "준비 중",
    contentGuide: "홀덤 가이드",
    contentGuideSubtitle: "핸드 순위와 기본 규칙",
    contentSeason: "시즌 랭킹",
    contentSeasonSubtitle: "이번 시즌 상위 플레이어",
    contentCommunity: "커뮤니티",
    contentCommunitySubtitle: "공지와 소식",
    nav: { home: "홈", game: "게임", tournament: "대회", season: "시즌·랭킹", profile: "프로필" },
  },
  action: { fold: "폴드", check: "체크", call: "콜", bet: "벳", raise: "레이즈", allIn: "올인" },
  table: { totalPot: "총 팟", move: "테이블 이동", sitOut: "자리비움", rules: "게임 규칙" },
} as const;
